apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: poc-compare
data:
  prometheus.yml: |
    global:
      scrape_interval: 5s
      evaluation_interval: 5s

    scrape_configs:
      - job_name: 'fastapi'
        static_configs:
          - targets: ['fastapi:80']
            labels:
              service: 'fastapi'
              environment: 'kubernetes'

      - job_name: 'golang'
        static_configs:
          - targets: ['golang:80']
            labels:
              service: 'golang'
              environment: 'kubernetes'

      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']
