global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'fastapi'
    static_configs:
      - targets: ['fastapi:8000']
        labels:
          service: 'fastapi'
          environment: 'local'

  - job_name: 'golang'
    static_configs:
      - targets: ['golang:8000']
        labels:
          service: 'golang'
          environment: 'local'

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
